services:

  mongodb:
    image: mongo:4.4
    container_name: skillgap-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
      MONGO_INITDB_DATABASE: skillgap
    volumes:
      - mongodb_data:/data/db
    networks:
      - skillgap-network

  backend:
    build:
      context: ./backend
      dockerfile: backend/Dockerfile
    container_name: skillgap-backend
    restart: unless-stopped
    environment:
      MONGO_URI: mongodb://admin:admin123@mongodb:27017/skillgap?authSource=admin
      MONGO_DB_NAME: skillgap
    ports:
      - "5678:5678"
    depends_on:
      - mongodb
    networks:
      - skillgap-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: skillgap-frontend
    restart: unless-stopped
    ports:
      - "8050:80"
    depends_on:
      - backend
    networks:
      - skillgap-network

networks:
  skillgap-network:

volumes:
  mongodb_data: