name: DevSecOps

on:
  push:
    

jobs:     

   # Code quality analysis
  code-quality:
    uses: ./.github/workflows/Code-quality.yml

  # Secret Scanning 
  secret-scaning:
    uses: ./.github/workflows/secret-scanning.yml

  #dependency-scan
  dependencies-scan:
    uses: ./.github/workflows/Dependency-scan.yml  

  # Docker image security scanning
  docker-scan:
    uses: ./.github/workflows/Docker-scan.yml
    secrets: inherit

  # SonarQube code analysis
  sonar-scan:
    uses: ./.github/workflows/Sonar-scan.yml
    secrets: inherit   

  # Code Tests
  code-tests:
    uses: ./.github/workflows/Code-test.yml  

  # push-to-docker-hub:
  docker-push:
    uses: ./.github/workflows/Docker-push.yml
    needs: [code-quality,code-tests,sonar-scan,docker-scan,dependencies-scan,secret-scanning]
    secrets: inherit  

  ## ---- CD -----
  deploy:
    needs: [docker-push]
    uses: ./.github/workflows/deploy.yml
    secrets: inherit

  dast-scan:
    needs: [deploy]
    uses: ./.github/workflows/Dast.yml
    secrets: inherit   