name: DevSecOps

on:
  push:

jobs:

  # -------------------------
  # CI - Security & Quality
  # -------------------------

  code-quality:
    uses: ./.github/workflows/Code-quality.yml

  secret-scanning:
    uses: ./.github/workflows/secret-scanning.yml

  dependencies-scan:
    uses: ./.github/workflows/Dependency-scan.yml

  docker-scan:
    uses: ./.github/workflows/Docker-scan.yml
    secrets: inherit

  sonar-scan:
    uses: ./.github/workflows/Sonar-scan.yml
    secrets: inherit

  code-tests:
    uses: ./.github/workflows/Code-test.yml


  # -------------------------
  # Docker Push
  # -------------------------

  docker-push:
    needs:
      - code-quality
      - secret-scanning
      - dependencies-scan
      - docker-scan
      - sonar-scan
      - code-tests

    uses: ./.github/workflows/Docker-push.yml
    secrets: inherit


  # -------------------------
  # CD - Deploy
  # -------------------------

  deploy:
    needs:
      - docker-push

    uses: ./.github/workflows/deploy.yml
    secrets: inherit


  # -------------------------
  # DAST
  # -------------------------

  dast-scan:
    needs:
      - deploy

    uses: ./.github/workflows/DAST.yml
    secrets: inherit