name: DevSecOps

on:
  push:
    

jobs:     

   # Code quality analysis
  code-quality:
    uses: ./.github/workflows/Code-quality.yml

  # Secret Scanning 
  secert-scaning:
    uses: ./.github/workflows/secret-scanning.yml