name: Python Backend Build

on: 
  workflow_call:
    

jobs:
  code-format:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python: ['3.11' ,'3.12','3.12']    

    steps:
      - name: Checkout Code
        uses: actions/checkout@v7

      - name: Set up Python
        uses: actions/setup-python@v7
        with:
          python-version: ${{ matrix.python }}
          cache: pip
          cache-dependency-path: backend/requirements.txt

      - name: Install Dependencies
        run: python -m pip install -r requirements.txt
        working-directory: backend    